# Generated by Django 3.2.7 on 2021-09-25 05:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='code',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
