# Generated by Django 3.2.7 on 2021-09-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeblog', '0003_auto_20210925_1357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='Content',
        ),
    ]
